### ISSUE TITLE
Add Adam Johnson's copyright attribution

### ISSUE THREAD

**Issue by joshuadavidthomas** [franciscobmacedo/lucide#2]
### Description

Thanks for creating this library. I was actually about to do the same thing by forking @adamchainz's `heroicons` repo and swapping out the Heroicon specific bits with Lucide, so I'm glad to see someone beat me to the punch.

However, I did notice Adam's copyright notice is nowhere in this repo. I know you shout him out at the bottom of the README, but given that the original package is MIT and that one of the stipulations of that license is copyright attribution, I believe this library should carry his copyright.

**Comment by adamchainz** [comment]
You can change the license to say "2021 Adam Johnson, 2024 Francisco Macedo", and that should be enough.

**Comment by franciscobmacedo** [comment]
Sorry for the delay, of course, this makes sense. I didn't know this was a stipulation of the license. Thanks for pointing it out!
